# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Calendar
on:
  repository_dispatch:
    types: [on-demand-calendar]
  schedule:
    - cron:  '0 1 1,20 * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r req_calendar.txt
    - name: Run script
      run: |
        python er_calendar.py
    - name: git setting
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: Commit files
      run: |
        git add -N .
        if ! git diff --exit-code --quiet
        then
          git add .
          git commit -m "Add csv" -a
          git push
        fi
