name: Daily

on:
  repository_dispatch:
    types: [on-demand-test]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r req_daily.txt
    - name: Run script
      run: |
        python er_daily.py
      env:
        BEARER_TOKEN: ${{ secrets.ER_BEARER_TOKEN }}
        CONSUMER_KEY: ${{ secrets.ER_CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.ER_CONSUMER_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ER_ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ER_ACCESS_TOKEN_SECRET }}
        AT_USER: ${{ secrets.ER_AT_USER }}
        AT_PASS: ${{ secrets.ER_AT_PASS }}
        URL: ${{ secrets.URL }}
