name: Daily

on:
  repository_dispatch:
    types: [on-demand-test]
  schedule:
    - cron:  '0 22 * * *'
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r req_daily.txt
    - name: Run script
      run: |
        python er_daily.py
      env:
        BEARER_TOKEN: ${{ secrets.ER_BEARER_TOKEN }}
        CONSUMER_KEY: ${{ secrets.ER_CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.ER_CONSUMER_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ER_ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ER_ACCESS_TOKEN_SECRET }}
