# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Make data.json

on:
  repository_dispatch:
    types: [on-demand-test]
  schedule:
    - cron: '0 17 * * 1'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f req_imabari.txt ]; then pip install -r req_imabari.txt; fi
        
    - name: Run script
      run: |
        python er_imabari.py
      env:
        URL: ${{ secrets.URL }}
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
        
  deploy:
    needs: build
    
    permissions:
      contents: read
      pages: write
      id-token: write
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: dist
        
    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v1
      with:
        path: './dist'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
